blank_issues_enabled: false
contact_links:
  - name: VĐT Suppor
    url: https://github.com/ZeraKage
    about: Please ask and answer questions here.
  - name: Fca-Sumi-Remake Bug 
    url: https://github.com/ZeraKage/Fca-Zera-Remake/issues
    about: Please report security vulnerabilities here.
